import Engine from '../src/indexing/engine';
import { titleRecord, renderFragment } from '../src/rendering/adapters';
import { TFile } from 'obsidian';
import { diagramProcessor } from '../src/ui/diagram-modal';
import { DiagramEditor } from '../src/diagrams/editor';
import { diagramFence, parseDiagram, type DiagramData } from '../src/diagrams/model';
import { renderDiagram } from '../src/diagrams/render';
import { waitForTikz } from '../src/export/tikz';
import { prepareMediaForPrint } from '../src/export/pagination';
const check = (condition: unknown, message: string) => { if (!condition) throw new Error(message); };
const settle = () => new Promise(resolve => setTimeout(resolve, 120));
export const tensorDiagram: DiagramData = { version: 1, grid: 2,
  nodes: [{ id: 'n-0-0', row: 0, col: 0, label: 'M \\times N' }, { id: 'n-0-1', row: 0, col: 1, label: 'M \\otimes_R N' }, { id: 'n-1-1', row: 1, col: 1, label: 'P' }],
  arrows: [{ id: 'a-1', from: 'n-0-0', to: 'n-0-1', label: '\\tau', style: 'solid', side: 'above' }, { id: 'a-2', from: 'n-0-0', to: 'n-1-1', label: 'b', style: 'solid', side: 'below' }, { id: 'a-3', from: 'n-0-1', to: 'n-1-1', label: '\\exists! \\widetilde{b}', style: 'dashed', side: 'below' }] };
export async function runFeatureRegressions() {
  const host = document.body.createDiv({ cls: 'markdown-rendered' });
  const notes = [Engine.parse('a.md', '> [!claim] A claim\n> Statement.\n\n^claim-a'), Engine.parse('b.md', '> [!proof][[a#^claim-a]]\n> Argument.\n\n> [!proof]\n> New-line argument.')];
  const graph = Engine.graph(notes);
  const proof = host.createDiv({ cls: 'callout', attr: { 'data-callout': 'proof' } });
  const title = proof.createDiv({ cls: 'callout-title' }).createDiv({ cls: 'callout-title-inner' });
  const link = title.createEl('a', { text: 'original reference', cls: 'internal-link', attr: { 'data-href': 'a#^claim-a' } });
  proof.createDiv({ cls: 'callout-content' }).createEl('p', { text: 'Argument.' }); titleRecord(proof, notes[1].theorems[0], graph);
  check(title.querySelector('.phb-type-label')?.textContent === 'Proof of' && link.textContent === 'clm 1', 'Proof reference title must use its resolved type and number');
  const standalone = host.createDiv({ cls: 'callout', attr: { 'data-callout': 'proof' } });
  standalone.createDiv({ cls: 'callout-title' }).createDiv({ cls: 'callout-title-inner', text: 'Proof' });
  const body = standalone.createDiv({ cls: 'callout-content' }).createEl('p', { text: 'Argument on the next line.' }); titleRecord(standalone, notes[1].theorems[1], graph);
  check(getComputedStyle(standalone.querySelector('.callout-title')!).cssFloat === 'none', 'Empty Proof header must occupy its own line');
  check(body.getBoundingClientRect().top >= standalone.querySelector('.callout-title')!.getBoundingClientRect().bottom - 1, 'Proof body must begin below its title');
  let saved: DiagramData | null = null;
  const editorHost = host.createDiv(); const editor = new DiagramEditor(editorHost, undefined, async data => { saved = data; });
  const click = (selector: string) => editorHost.querySelector<HTMLButtonElement>(selector)!.click();
  click('[data-an-node="n-0-0"]'); click('[data-an-node="n-0-1"]');
  editor.mode = 'arrows'; click('[data-an-node="n-0-0"]'); click('[data-an-node="n-0-1"]');
  editor.arrowLabel.value = '\\alpha'; editor.arrowLabel.dispatchEvent(new Event('input'));
  editor.style.value = 'dashed'; editor.style.dispatchEvent(new Event('change'));
  check(editor.data.arrows.length === 1 && editor.data.arrows[0].label === '\\alpha' && editor.data.arrows[0].style === 'dashed', 'Point clicks must create editable labelled arrows');
  editor.gridSelect.value = '3'; editor.gridSelect.dispatchEvent(new Event('change')); editor.mode = 'nodes'; click('[data-an-node="n-2-2"]');
  editor.gridSelect.value = '2'; editor.gridSelect.dispatchEvent(new Event('change'));
  check(editor.data.nodes.every(n => n.row < 2 && n.col < 2), 'Grid shrinking must remove out-of-grid nodes');
  click('[data-an-action="undo"]'); check(editor.data.grid === 3 && editor.data.nodes.some(n => n.row === 2), 'Undo must restore removed nodes');
  click('[data-an-action="save"]'); await settle(); check(saved && parseDiagram(JSON.stringify(saved)).arrows.length === 1, 'Save must persist a valid diagram');
  await settle();
  editorHost.querySelector('g[data-an-arrow]')!.dispatchEvent(new MouseEvent('click', { bubbles: true })); await settle();
  check(editor.selectedArrow === editor.data.arrows[0].id, 'Tapping the preview must select an editable arrow');
  click('[data-an-action="remove-arrow"]'); check(editor.data.arrows.length === 0, 'Selected preview arrow must be removable');
  editorHost.remove();
  const fixture = host.createDiv({ cls: 'an-diagram-figure' }); const svg = await renderDiagram(fixture, tensorDiagram);
  check(svg.querySelectorAll('svg.an-diagram-math').length === 6 && !svg.querySelector('foreignObject') && !svg.querySelector('[data-mml-node="merror"]'), 'Node and arrow labels must share pure SVG coordinates with arrows');
  const selectable = host.createDiv(); let picked = '';
  await renderDiagram(selectable, tensorDiagram, id => { picked = id; });
  selectable.querySelector('g[data-an-arrow="a-1"]')!.dispatchEvent(new MouseEvent('click', { bubbles: true }));
  check(picked === 'a-1' && !!selectable.querySelector('path[pointer-events="stroke"]'), 'Touch-sized arrow targets must select arrows'); selectable.remove();
  check(svg.querySelectorAll('path[marker-end]').length === 3 && svg.querySelector('[stroke-dasharray]'), 'Arrow geometry and dashed style must survive rendering');
  for (const width of [300, 700]) {
    fixture.style.width = width + 'px';
    const bounds = svg.getBoundingClientRect(), scale = bounds.width / 460;
    const labels = [...svg.querySelectorAll<SVGSVGElement>(':scope > svg.an-diagram-math')];
    check(Math.abs((labels[0].getBoundingClientRect().left + labels[0].getBoundingClientRect().width / 2 - bounds.left) / scale - 110) < 1, 'Resizing must preserve the source-node SVG center');
    const arrow = svg.querySelector<SVGPathElement>('g[data-an-arrow="a-1"] path[marker-end]')!.getBoundingClientRect();
    check(Math.abs((arrow.top - bounds.top) / scale - 85) < 1, 'Resizing must keep the horizontal arrow on the node row');
  }
  fixture.style.removeProperty('width');
  const again = host.createDiv({ cls: 'an-diagram-figure' }); const second = await renderDiagram(again, tensorDiagram);
  check(svg.querySelector('marker')!.id !== second.querySelector('marker')!.id, 'Multiple diagrams must have independent markers');
  const glyphIds = [...host.querySelectorAll('[id]')].map(n => n.id); check(new Set(glyphIds).size === glyphIds.length, 'Cloned formula glyphs must have unique IDs');
  again.remove();
  const diagramSource = diagramFence({ ...tensorDiagram, caption: 'Shared numbering' });
  let content = 'Before\n\n' + diagramSource + '\n\n^diagram\n\nAfter';
  const file = new TFile(); const changes: string[] = [];
  const app: any = { workspace: { getActiveViewOfType: () => null }, vault: { getAbstractFileByPath: () => file, read: async () => content, process: async (_file: unknown, update: (text: string) => string) => { content = update(content); changes.push(content); } } };
  const rendered = host.createDiv();
  const ctx: any = { sourcePath: 'diagram.md', getSectionInfo: () => ({ lineStart: 2, lineEnd: 99 }) };
  await diagramProcessor(app, JSON.stringify({ ...tensorDiagram, caption: 'Shared numbering' }, null, 2), rendered, ctx);
  const diagramNote = Engine.parse('diagram.md', content), diagramGraph = Engine.graph([diagramNote]);
  renderFragment(rendered, diagramNote, diagramGraph, () => ctx.getSectionInfo());
  check(rendered.querySelector('.an-caption-label')?.textContent === 'Figure 1' && !rendered.querySelector<HTMLElement>('.an-diagram-caption')!.hidden, 'Standalone diagram must display the shared figure counter');
  const exportDiagram = rendered.cloneNode(true) as HTMLElement; exportDiagram.querySelector('.an-diagram-actions')!.remove(); exportDiagram.dataset.phbBlock = 'diagram';
  const diagramMarkup = exportDiagram.outerHTML;
  rendered.querySelector<HTMLButtonElement>('.an-diagram-delete')!.click(); await settle();
  check(changes.length === 1 && !content.includes('academic-diagram') && !content.includes('^diagram') && content.includes('Before') && content.includes('After'), 'Rendered deletion must work without opening source mode and preserve surrounding text');
  const hidden = rendered.querySelector<HTMLElement>('.an-diagram-caption')!; hidden.hidden = true;
  check(getComputedStyle(hidden).display === 'none', 'Wrapped or unindexed diagrams must not display a second caption');
  rendered.remove();
  const tikz = host.createDiv();
  const firstBlock = tikz.createDiv({ cls: 'block-language-tikz' }); const secondBlock = tikz.createDiv({ cls: 'block-language-tikz' });
  window.setTimeout(() => { for (const block of [firstBlock, secondBlock]) { const picture = document.createElementNS('http://www.w3.org/2000/svg', 'svg'); const path = document.createElementNS(picture.namespaceURI, 'path'); path.id = 'glyph'; const use = document.createElementNS(picture.namespaceURI, 'use'); use.setAttribute('href', '#glyph'); picture.append(path, use); block.appendChild(picture); } }, 150);
  await waitForTikz(tikz, 1000);
  check(firstBlock.querySelector('path')!.id !== secondBlock.querySelector('path')!.id, 'TikZ glyph IDs must be isolated');
  for (const block of [firstBlock, secondBlock]) check(block.querySelector('use')!.getAttribute('href') === '#' + block.querySelector('path')!.id, 'TikZ glyph references must remain connected');
  const unfinished = host.createDiv(); unfinished.createDiv({ cls: 'block-language-tikz' });
  let timedOut = false; try { await waitForTikz(unfinished, 10); } catch { timedOut = true; } check(timedOut, 'Unfinished TikZ must stop export');
  const missing = host.createDiv(); missing.createEl('pre').createEl('code', { cls: 'language-tikz' });
  let unavailable = false; try { await waitForTikz(missing); } catch { unavailable = true; } check(unavailable, 'Missing TikZJax must stop export with an error');
  unfinished.remove(); missing.remove(); tikz.remove();
  const tall = host.createDiv({ cls: 'callout an-media', attr: { 'data-callout': 'figure' } });
  const caption = tall.createDiv({ cls: 'callout-title', text: 'Tall picture caption.' });
  const image = tall.createDiv({ cls: 'callout-content' }).createEl('img', { attr: { src: 'data:image/svg+xml,' + encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="600" height="1800"><rect width="600" height="1800" fill="teal"/></svg>') } });
  await image.decode(); const report = prepareMediaForPrint();
  check(report.scaled >= 1 && !tall.classList.contains('an-print-oversized') && tall.getBoundingClientRect().height < 950, 'Oversized pictures must fit the usable A4 height');
  check(tall.lastElementChild === caption, 'Print protection must retain captions below pictures');
  const proofMarkup = proof.outerHTML + standalone.outerHTML;
  tall.remove(); proof.remove(); standalone.remove();
  // Leave this synthetic figure for the README screenshot and PDF fixture.
  host.id = 'an-diagram-test-fixture';
  return { message: 'Proof titles, responsive pure-SVG diagrams, touch selection, direct deletion, shared numbering, TikZ waiting and picture fitting passed', svg: svg.outerHTML, diagramMarkup, fence: diagramFence(tensorDiagram), proofMarkup };
}
